const ADD_SOUND = 'SOUND/ADD'
const DELETE_SOUND = 'SOUND/DELETE'
const EDIT_SOUND = 'SOUND/EDIT'
const EDIT_ICON = 'SOUND/ICON'
const EDIT_URL = 'SOUND/URL'
const RESET = 'SOUND/RESET'
const GET_DRAWER = 'DRAWER/GET'
const SET_DRAWER = 'DRAWER/SET'

const Types = {
	ADD_SOUND,
	DELETE_SOUND,
	EDIT_SOUND,
	EDIT_ICON,
	EDIT_URL,
	RESET,
	GET_DRAWER,
	SET_DRAWER
}


export default Types